<!-- scripts (jquery) -->
<script src="<%=path %>/resources/js/jquery/jquery-1.4.3.js" type="text/javascript"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.cookie.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.form.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.metadata.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.validate.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.validate.methods.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.validate.cn.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.dimensions.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.jqDnR.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.jqModal.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.tools.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.qtip.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.pager.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.livequery.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.superfish.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.hoverIntent.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.datepicker.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.bCheckbox.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.lSelect.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.ajaxfileupload.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/js/jquery.zoomimage.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/tiny_mce/jquery.tinymce.js"></script>
<script type="text/javascript" src="<%=path %>/resources/common/tiny_mce/jquery.tinymce.js"></script>

