package com.eh.base.entity;

import java.util.Date;


/**
 * VDeptInfo generated by MyEclipse Persistence Tools
 */

public class DeptInfo  implements java.io.Serializable {

	public final static Long ROOT_DEPT_ID = Long.valueOf(1);
    // Fields    

     private Long deptId;
     private String deptCode;
     private String deptName;
     private Long deptKind;
     private Long deptStatus;
     private Long sortNum;
     private Long adminId;
     private String linkMan;
     private String linkTel;
     private Long createUser;
     private Date createDate;
     private Date updateDate;
     private Long updateUser;
     private DeptInfo parent;
     private String treeNo;
     private String fullName;
     private boolean isLeaf;


    // Constructors

    /** default constructor */
    public DeptInfo() {
    }

	/** minimal constructor */
    public DeptInfo(Long deptId) {
        this.deptId = deptId;
    }
    
    /** full constructor */
    public DeptInfo(Long deptId, String deptCode, String deptName, Long deptKind, Long deptStatus, Long sortNum, Long adminId, String linkMan, String linkTel, Long createUser, Date createDate, Date updateDate, Long updateUser, DeptInfo parent, String treeNo, String fullName) {
        this.deptId = deptId;
        this.deptCode = deptCode;
        this.deptName = deptName;
        this.deptKind = deptKind;
        this.deptStatus = deptStatus;
        this.sortNum = sortNum;
        this.adminId = adminId;
        this.linkMan = linkMan;
        this.linkTel = linkTel;
        this.createUser = createUser;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.parent = parent;
        this.treeNo = treeNo;
        this.fullName = fullName;
    }

   
    // Property accessors

    public Long getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    public String getDeptCode() {
        return this.deptCode;
    }
    
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    public Long getDeptKind() {
        return this.deptKind;
    }
    
    public void setDeptKind(Long deptKind) {
        this.deptKind = deptKind;
    }

    public Long getDeptStatus() {
        return this.deptStatus;
    }
    
    public void setDeptStatus(Long deptStatus) {
        this.deptStatus = deptStatus;
    }

    public Long getSortNum() {
        return this.sortNum;
    }
    
    public void setSortNum(Long sortNum) {
        this.sortNum = sortNum;
    }

    public Long getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    public String getLinkMan() {
        return this.linkMan;
    }
    
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan;
    }

    public String getLinkTel() {
        return this.linkTel;
    }
    
    public void setLinkTel(String linkTel) {
        this.linkTel = linkTel;
    }

    public Long getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public Long getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    public DeptInfo getParent() {
        return this.parent;
    }
    
    public void setParent(DeptInfo parent) {
        this.parent = parent;
    }

    public DeptInfo getOrg(){
    	if (this.parent == null || (this.deptKind != null && this.deptKind.longValue() == Long.valueOf(1))){
    		return this;
    	}else{
    		return this.getOrg();
    	}
    }
    
    public String getTreeNo() {
        return this.treeNo;
    }
    
    public void setTreeNo(String treeNo) {
        this.treeNo = treeNo;
    }

    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

	public boolean isLeaf() {
		return isLeaf;
	}

	public void setLeaf(boolean isLeaf) {
		this.isLeaf = isLeaf;
	}
   








}