package com.eh.base.entity;

import java.util.Date;


/**
 * TbAttachment generated by MyEclipse Persistence Tools
 */

public class TbAttachment  implements java.io.Serializable {


    // Fields    

     private Long recId;
     private String fileName;
     private String fileExtension;
     private String attactType;
     private String fileSize;
     private String fileLoaction;
     private Long userId;
     private Date createDate;


    // Constructors

    /** default constructor */
    public TbAttachment() {
    }

    
    /** full constructor */
    public TbAttachment(String fileName, String fileExtension, String attactType, String fileSize, String fileLoaction, Long userId, Date createDate) {
        this.fileName = fileName;
        this.fileExtension = fileExtension;
        this.attactType = attactType;
        this.fileSize = fileSize;
        this.fileLoaction = fileLoaction;
        this.userId = userId;
        this.createDate = createDate;
    }

   
    // Property accessors

    public Long getRecId() {
        return this.recId;
    }
    
    public void setRecId(Long recId) {
        this.recId = recId;
    }

    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileExtension() {
        return this.fileExtension;
    }
    
    public void setFileExtension(String fileExtension) {
        this.fileExtension = fileExtension;
    }

    public String getAttactType() {
        return this.attactType;
    }
    
    public void setAttactType(String attactType) {
        this.attactType = attactType;
    }

    public String getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    public String getFileLoaction() {
        return this.fileLoaction;
    }
    
    public void setFileLoaction(String fileLoaction) {
        this.fileLoaction = fileLoaction;
    }

    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
   








}