package com.eh.base.entity;



/**
 * TbDeptRel generated by MyEclipse Persistence Tools
 */

public class TbDeptRel  implements java.io.Serializable {


    // Fields    

     private Long recId;
     private TbDeptInfo dept;
     private Long relType;
     private TbDeptInfo parent;
     private String treeNo;
     private String fullName;


    // Constructors

    /** default constructor */
    public TbDeptRel() {
    }

	/** minimal constructor */
    public TbDeptRel(TbDeptInfo dept) {
        this.dept = dept;
    }
    
    /** full constructor */
    public TbDeptRel(TbDeptInfo dept, Long relType, TbDeptInfo parent, String treeNo, String fullName) {
        this.dept = dept;
        this.relType = relType;
        this.parent = parent;
        this.treeNo = treeNo;
        this.fullName = fullName;
    }

   
    // Property accessors

    public Long getRecId() {
        return this.recId;
    }
    
    public void setRecId(Long recId) {
        this.recId = recId;
    }

    public TbDeptInfo getDept() {
        return this.dept;
    }
    
    public void setDept(TbDeptInfo dept) {
        this.dept = dept;
    }

    public Long getRelType() {
        return this.relType;
    }
    
    public void setRelType(Long relType) {
        this.relType = relType;
    }

    public TbDeptInfo getParent() {
        return this.parent;
    }
    
    public void setParent(TbDeptInfo parent) {
        this.parent = parent;
    }

    public String getTreeNo() {
        return this.treeNo;
    }
    
    public void setTreeNo(String treeNo) {
        this.treeNo = treeNo;
    }

    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
   








}