package com.eh.base.entity;



/**
 * MenuInfo generated by MyEclipse Persistence Tools
 */

public class TbMenuInfo  implements java.io.Serializable {


    // Fields    

     private Long menuId;
     private TbMenuInfo parent;
     private Long menuCode;
     private String menuName;
     private String menuUrl;
     private Long resType;
     private Long sortNum;
     private Long status;
     private String treeNo;
     private Long isLeaf;

    // Constructors

    /** default constructor */
    public TbMenuInfo() {
    }

    
    /** full constructor */
    public TbMenuInfo(TbMenuInfo parent, Long menuCode, String menuName, String menuUrl, Long resType, Long sortNum, Long status, String treeNo) {
        this.parent = parent;
        this.menuCode = menuCode;
        this.menuName = menuName;
        this.menuUrl = menuUrl;
        this.resType = resType;
        this.sortNum = sortNum;
        this.status = status;
        this.treeNo = treeNo;
    }

   
    // Property accessors

    public Long getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    public TbMenuInfo getParent() {
        return this.parent;
    }
    
    public void setParent(TbMenuInfo parent) {
        this.parent = parent;
    }

    public Long getMenuCode() {
        return this.menuCode;
    }
    
    public void setMenuCode(Long menuCode) {
        this.menuCode = menuCode;
    }

    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public String getMenuUrl() {
        return this.menuUrl;
    }
    
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    public Long getResType() {
        return this.resType;
    }
    
    public void setResType(Long resType) {
        this.resType = resType;
    }

    public Long getSortNum() {
        return this.sortNum;
    }
    
    public void setSortNum(Long sortNum) {
        this.sortNum = sortNum;
    }

    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }

    public String getTreeNo() {
        return this.treeNo;
    }
    
    public void setTreeNo(String treeNo) {
        this.treeNo = treeNo;
    }


	public Long getIsLeaf() {
		return isLeaf;
	}
	
	public boolean isLeaf(){
		if(this.isLeaf!=null&&this.isLeaf.longValue()==Long.valueOf(1)){
			return true;
		}else{
			return false;
		}
	}


	public void setIsLeaf(Long isLeaf) {
		this.isLeaf = isLeaf;
	}


}