package com.eh.base.entity;



/**
 * TbResRel generated by MyEclipse Persistence Tools
 */

public class TbResRel  implements java.io.Serializable {
	
	public final static String ROLE = "R";
	public final static String DEPT = "D";
	public final static String USER = "U";
    // Fields    

     private Long recId;
     private Long objId;
     private String relType;
     private TbMenuInfo menu;


    // Constructors

    /** default constructor */
    public TbResRel() {
    }

    
    /** full constructor */
    public TbResRel(Long objId, String relType, TbMenuInfo menu) {
        this.objId = objId;
        this.relType = relType;
        this.menu = menu;
    }

   
    // Property accessors

    public Long getRecId() {
        return this.recId;
    }
    
    public void setRecId(Long recId) {
        this.recId = recId;
    }

    public Long getObjId() {
        return this.objId;
    }
    
    public void setObjId(Long objId) {
        this.objId = objId;
    }

    public String getRelType() {
        return this.relType;
    }
    
    public void setRelType(String relType) {
        this.relType = relType;
    }

    public TbMenuInfo getMenu() {
        return this.menu;
    }
    
    public void setMenu(TbMenuInfo menu) {
        this.menu = menu;
    }
   








}