package com.eh.base.entity;

/**
 * TbUdrRel generated by MyEclipse Persistence Tools
 */

public class TbUdrRel implements java.io.Serializable {

	// Fields

	private Long recId;
	
	private TbUserInfo userInfo;
	
	private TbDeptInfo deptInfo;
	
	private TbRoleInfo roleInfo;
	

	// Constructors

	/** default constructor */
	public TbUdrRel() {
	}


	public Long getRecId() {
		return recId;
	}


	public void setRecId(Long recId) {
		this.recId = recId;
	}


	public TbUserInfo getUserInfo() {
		return userInfo;
	}


	public void setUserInfo(TbUserInfo userInfo) {
		this.userInfo = userInfo;
	}


	public TbDeptInfo getDeptInfo() {
		return deptInfo;
	}


	public void setDeptInfo(TbDeptInfo deptInfo) {
		this.deptInfo = deptInfo;
	}


	public TbRoleInfo getRoleInfo() {
		return roleInfo;
	}


	public void setRoleInfo(TbRoleInfo roleInfo) {
		this.roleInfo = roleInfo;
	}

	
}