package com.eh.base.entity;

import java.util.Date;

import com.eh.base.util.DateUtil;

/**
 * TbUserInfo generated by MyEclipse Persistence Tools
 */

public class TbUserInfo implements java.io.Serializable {

	// Fields

	private Long userId;
	private String userCode;
	private String loginPwd;
	private Long status;
	private String userName;
	private DeptInfo dept;
	private Long sex;
	private Date birthday;
	private Long age;
	private String job;
	private String mobile;
	private String email;
	private String edu;
	private String eduShcool;

	// Constructors

	/** default constructor */
	public TbUserInfo() {
	}

	/** full constructor */
	public TbUserInfo(String userCode, String loginPwd, Long status,
			String userName, DeptInfo dept, Long sex, Date birthday, Long age,
			String job, String mobile, String email, String edu,
			String eduShcool) {
		this.userCode = userCode;
		this.loginPwd = loginPwd;
		this.status = status;
		this.userName = userName;
		this.dept = dept;
		this.sex = sex;
		this.birthday = birthday;
		this.age = age;
		this.job = job;
		this.mobile = mobile;
		this.email = email;
		this.edu = edu;
		this.eduShcool = eduShcool;
	}

	// Property accessors

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getLoginPwd() {
		return this.loginPwd;
	}

	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public DeptInfo getDept() {
		return this.dept;
	}

	public void setDept(DeptInfo dept) {
		this.dept = dept;
	}

	public Long getSex() {
		return this.sex;
	}

	public void setSex(Long sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Long getAge() {
		return this.age;
	}

	public void setAge(Long age) {
		this.age = age;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEdu() {
		return this.edu;
	}

	public void setEdu(String edu) {
		this.edu = edu;
	}

	public String getEduShcool() {
		return this.eduShcool;
	}

	public void setEduShcool(String eduShcool) {
		this.eduShcool = eduShcool;
	}

	public String getBirthdayStr() {
		return DateUtil.getInstance().formateDate(this.birthday,
				DateUtil.DF_YYYY_MM_DD);
	}

}